(() => {
  const current=window.BESTIARY_DATA, history=window.BESTIARY_HISTORY||[];
  if(!current?.models?.length) throw new Error('Frontier data did not load');
  const dims=[['overall','Capability mass'],['reasoning','Crown'],['coding','Claws'],['agentic','Autonomy'],['multimodal','Senses'],['knowledge','Armor'],['math','Fangs']];
  const pos=[[13.5,51],[38.5,51],[63.5,51],[87.5,51]];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const value=(m,d)=>d==='overall'?m.overall:m.categories?.[d];
  const scale=v=>v==null ? .985 : Math.max(.985,Math.min(1.045,.985+(v-55)/500));
  let dimension='overall', selected=null, active=history.length?history.length-1:0, data=current;

  function priorFor(m){return active>0?history[active-1]?.models?.find(p=>p.provider===m.provider):null}
  function evolution(m,d){const p=priorFor(m);if(!p)return active>0?'NEW':'';if(p.slug!==m.slug)return'EVOLVED';const a=d==='overall'?p.overall:p.categories?.[d],b=value(m,d);if(a==null||b==null)return'';const delta=b-a;return Math.abs(delta)<.005?'':`${delta>0?'▲':'▼'}${Math.abs(delta).toFixed(2)}`}
  function snapshotAt(i){if(i>=history.length-1)return current;const s=history[i],base=new Map(current.models.map(m=>[m.provider,m]));return{...current,date:s.date,sourceUpdated:s.date,models:s.models.map(m=>({...base.get(m.provider),...m}))}}
  function rings(m,i){const v=value(m,dimension),c=m.colors[0],radius=36+(v??50)*.18;return `<svg class="specimen-rings" viewBox="0 0 300 220" aria-hidden="true"><ellipse cx="150" cy="118" rx="${radius*1.55}" ry="${radius*.62}" fill="none" stroke="${c}" stroke-opacity=".8" stroke-width="1.2" stroke-dasharray="3 8"/><ellipse cx="150" cy="118" rx="${radius*1.18}" ry="${radius*.46}" fill="none" stroke="${c}" stroke-opacity=".35"/><path d="M36 118h25m178 0h25M150 36v18m0 129v18" stroke="${c}" stroke-opacity=".65"/><g fill="${c}">${[0,1,2,3,4,5].map(n=>{const a=n*Math.PI/3,x=150+Math.cos(a)*radius*1.55,y=118+Math.sin(a)*radius*.62;return`<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${n%2?2:3}"/>`}).join('')}</g></svg>`}
  function card(m,i){const v=value(m,dimension),delta=evolution(m,dimension),s=scale(v);return `<button class="creature" data-index="${i}" style="left:${pos[i][0]}%;top:${pos[i][1]}%;--c:${m.colors[0]};--growth:${s}" aria-label="${esc(m.name)}, ${v==null?'unrated':v.toFixed(2)} ${dimension}">${rings(m,i)}<span class="threat-meter"><i style="height:${Math.max(12,(v??45))}%"></i></span><span class="creature-name"><span class="rank">${i+1}</span><span class="identity"><strong>${esc(m.name)}</strong><small>${esc(m.title)}</small></span><span class="score">${v==null?'—':v.toFixed(1)}<em class="${delta.startsWith('▼')?'down':''}">${esc(delta)}</em></span></span></button>`}
  function render(){
    app.innerHTML=`<section class="world"><img class="world-art" src="assets/bestiary-world.png" alt="Four monumental biomechanical frontier-model creatures displayed on luminous selection pedestals"><div class="vignette"></div><header class="masthead"><div><div class="kicker">LIVE MODEL CAPABILITY OBSERVATORY</div><h1>FRONTIER <em>BESTIARY</em></h1><p>Four provider flagships. One evolving frontier.</p></div><div class="seal">BENCHLM SNAPSHOT<strong>${esc(data.sourceUpdated||data.date)}</strong></div></header><div class="metric-label"><span>SELECTED TRAIT</span><b>${esc(dimension.toUpperCase())}</b></div><div class="arena">${data.models.map(card).join('')}</div><nav class="hud" aria-label="Capability controls"><div class="dims">${dims.map(([k,label])=>`<button data-dim="${k}" class="${dimension===k?'active':''}" title="${label}">${k}</button>`).join('')}</div><div class="timeline"><span>FIRST SIGHTING</span><input id="time" type="range" min="0" max="${Math.max(0,history.length-1)}" value="${active}" ${history.length<2?'disabled':''}><span>${esc(data.date)}</span></div><div class="legend">CREATURE SCALE + TARGET RING TRACK THE SELECTED CAPABILITY · CLICK OR PRESS 1–4 TO INSPECT</div></nav><aside class="detail" aria-live="polite"></aside></section>`;
    bind();if(selected!=null)openDetail(selected)
  }
  function bind(){document.querySelectorAll('[data-dim]').forEach(b=>b.onclick=()=>{dimension=b.dataset.dim;selected=null;render()});document.querySelectorAll('.creature').forEach(b=>{b.onclick=()=>openDetail(+b.dataset.index);b.onmouseenter=()=>focus(+b.dataset.index,true);b.onmouseleave=()=>{if(selected==null)focus(null,false)}});document.querySelector('#time')?.addEventListener('input',e=>{active=+e.target.value;data=snapshotAt(active);selected=null;render()})}
  function focus(i,on){document.querySelectorAll('.creature').forEach((el,n)=>{el.classList.toggle('muted',on&&n!==i);el.classList.toggle('selected',on&&n===i)})}
  function openDetail(i){selected=i;focus(i,true);const m=data.models[i],panel=document.querySelector('.detail');panel.style.setProperty('--c',m.colors[0]);panel.innerHTML=`<button class="close" aria-label="Close">×</button><div class="detail-kicker">SPECIMEN ${String(i+1).padStart(2,'0')} · ${esc(m.provider)}</div><h2>${esc(m.title)}</h2><p>${esc(m.name)} · ${esc(m.species)}</p><div class="big"><b>${m.overall.toFixed(2)}</b><span>OVERALL<br>CAPABILITY MASS</span></div>${Object.entries(m.categories).map(([k,v])=>`<div class="stat ${v==null?'unknown':''}"><span>${k}</span><div><i style="width:${v??0}%"></i></div><b>${v==null?'—':v.toFixed(1)}</b></div>`).join('')}<div class="facts"><div><span>CONTEXT</span><b>${esc(m.context)}</b></div><div><span>EVIDENCE</span><b>${esc(m.confidence)}</b></div><div><span>OUTPUT / 1M</span><b>${m.outputPrice==null?'—':`$${m.outputPrice}`}</b></div><div><span>FIRST SEEN</span><b>${esc(m.releaseDate||'—')}</b></div></div><a href="${esc(m.sourceUrl)}" target="_blank" rel="noreferrer">OPEN EVIDENCE RECORD ↗</a><small>Creature anatomy is metaphor. Exact scores remain authoritative; missing categories are never estimated.</small>`;panel.classList.add('open');panel.querySelector('.close').onclick=closeDetail}
  function closeDetail(){selected=null;document.querySelector('.detail')?.classList.remove('open');focus(null,false)}
  document.addEventListener('keydown',e=>{if(/^[1-4]$/.test(e.key))openDetail(+e.key-1);if(e.key==='Escape')closeDetail()});
  const app=document.querySelector('#app');render();
})();
